# /Users/zaadee/.config/tmuxinator/configs.yml

name: configs
root: ~/

windows:
  - nvim:
      root: ~/.config/nvim/
      panes:
        - vi
  - alacritty:
      root: ~/.config/alacritty/
      panes:
        - vi
  - tmux:
     root: ~/.config/tmux
     panes:
       - vi
  - zsh: vi .zshrc
