import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
padding = { x = 9, y = 0 }

[font]
size = 15.00
normal = { family = "M+1Code Nerd Font Propo", style = "Regular" }
italic = { family = "M+1Code Nerd Font Propo", style = "Light" }
offset = { x = 1, y = 2 }
glyph_offset = { x = 0, y = 1 }

[mouse]
hide_when_typing = true
