import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
padding = { x = 10, y = 10 }


[font]
normal = { family = "SauceCodePro Nerd Font Propo", style = "Regular" }
# bold = { family = "ComicShannsMono Nerd Font Propo", style = "Regular" }
# italic = { family = "ComicShannsMono Nerd Font Propo", style = "Regular" }

offset = { x = 0, y = 1 }
size = 15.00

[mouse]
hide_when_typing = true
