import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
padding = { x = 12, y = 2 }

[font]
size = 12.25
normal = { family = "M+CodeLatX Nerd Font", style = "Regular" }
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[mouse]
hide_when_typing = true
