import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
padding = { x = 15, y = 10 }


[font]
normal = { family = "SauceCodePro Nerd Font Propo", style = "Regular" }
offset = { x = 0, y = 0 }
size = 17.00

[mouse]
hide_when_typing = true
