import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
padding = { x = 5, y = 2 }

[font]
size = 15.00
normal = { family = "M+1Code Nerd Font Propo", style = "Regular" }
italic = { family = "M+1Code Nerd Font Propo", style = "Light" }
offset = { x = 2, y = 4 }
glyph_offset = { x = 0, y = 2 }

[mouse]
hide_when_typing = true
