import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
padding = { x = 10, y = 10 }

# test tyhis ss
[font]
size = 15.00
normal = { family = "M+1Code Nerd Font Propo", style = "Regular" }
italic = { family = "M+1Code Nerd Font Propo", style = "Light" }
offset = { x = 1, y = 6 }
glyph_offset = { x = 0, y = 3 }

[mouse]
hide_when_typing = true
